#!/usr/bin/bash

name=wayland
version=1.24.0
release=1
depends=glibc,libffi,expat,libxml2
source=https://gitlab.freedesktop.org/wayland/wayland/-/releases/$version/downloads/wayland-$version.tar.xz
license="MIT"

build()
{
    meson setup                  \
          --prefix=/usr          \
          --buildtype=release    \
          -D documentation=false \
          build
    meson compile -C build
    meson install -C build --destdir $DESTDIR
}
