#!/usr/bin/bash

name=acl
version=2.3.2
release=1
depends=glibc
source=https://download.savannah.gnu.org/releases/acl/acl-$version.tar.xz
license="LGPL-2.1-or-later AND GPL-2.0-or-later"

build()
{
   ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install 
}
