#!/usr/bin/bash

NAME=acl
VERSION=2.3.2
RELEASE=1
DEPENDS=glibc
SOURCE=https://download.savannah.gnu.org/releases/acl/acl-$VERSION.tar.xz
LICENSE="LGPL-2.1-or-later AND GPL-2.0-or-later"

build()
{
   ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install 
}
