#!/usr/bin/bash

NAME=fastfetch
VERSION=2.51.1
RELEASE=1
DEPENDS=glibc
SOURCE=https://github.com/fastfetch-cli/fastfetch/archive/$VERSION/fastfetch-$VERSION.tar.gz
LICENSE=""

build()
{
    mkdir build
    cd build
    cmake -D CMAKE_INSTALL_PREFIX=/usr \
          -D CMAKE_BUILD_TYPE=Release  \
          -D BUILD_FLASHFETCH=OFF      \
          ..
    make
    make DESTDIR=$DESTDIR install
}
