#!/usr/bin/bash

name=fastfetch
version=2.51.1
release=1
depends=glibc
source=https://github.com/fastfetch-cli/fastfetch/archive/$version/fastfetch-$version.tar.gz
license="MIT"

build()
{
    mkdir build
    cd build
    cmake -D CMAKE_INSTALL_PREFIX=/usr \
          -D CMAKE_BUILD_TYPE=Release  \
          -D BUILD_FLASHFETCH=OFF      \
          ..
    make
    make DESTDIR=$DESTDIR install
}
