#!/usr/bin/bash

NAME=libpsl
VERSION=0.21.5
RELEASE=1
DEPENDS=glibc
SOURCE=https://github.com/rockdaboot/libpsl/releases/download/$VERSION/libpsl-$VERSION.tar.gz
LICENSE="MIT"

build()
{
    ./configure --prefix=/usr --disable-static --disable-dependency-tracking
    make
    make DESTDIR=$DESTDIR install
}
