#!/usr/bin/bash

name=libpsl
version=0.21.5
release=1
depends=glibc
source=https://github.com/rockdaboot/libpsl/releases/download/$version/libpsl-$version.tar.gz
license="MIT"

build()
{
    ./configure --prefix=/usr --disable-static --disable-dependency-tracking
    make
    make DESTDIR=$DESTDIR install
}
