#!/usr/bin/bash

NAME=groff
VERSION=1.23.0
RELEASE=1
DEPENDS=glibc,perl,gcc
SOURCE=https://ftp.gnu.org/gnu/groff/groff-$VERSION.tar.gz
LICENSE="GPL-3.0-or-later"

build()
{
    PAGE=A4 ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
