#!/usr/bin/bash

name=groff
version=1.23.0
release=1
depends=glibc,perl,gcc
source=https://ftp.gnu.org/gnu/groff/groff-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    PAGE=A4 ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
