#!/usr/bin/bash

name=xz
version=5.8.1
release=1
depends=glibc,sh
source=https://tukaani.org/xz/xz-$version.tar.gz
license="LGPL-2.1-or-later OR GPL-2.0-or-later"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make install
}
