#!/usr/bin/bash

name=inetutils
version=2.6
release=1
depends=glibc,libcap,readline,ncurses,libxcrypt
source=https://ftp.gnu.org/gnu/inetutils/inetutils-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c
    ./configure --prefix=/usr        \
                --bindir=/usr/bin    \
                --localstatedir=/var \
                --disable-logger     \
                --disable-whois      \
                --disable-rcp        \
                --disable-rexec      \
                --disable-rlogin     \
                --disable-rsh        \
                --disable-servers
    make
    make DESTDIR=$DESTDIR install
    mkdir -p $DESTDIR/usr/sbin
    mv $DESTDIR/usr/{,s}bin/ifconfig
}
