#!/usr/bin/bash

name=icu
version=77.1
release=1
depends=glibc,gcc,sh
source=https://github.com/unicode-org/icu/releases/download/release-${VERSION//./-/}/icu4c-${VERSION//./_/}-src.tgz
license="BSD-2-Clause OR BSD-3-Clause"

build()
{
    cd source
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
