#!/usr/bin/bash

name=m4
version=1.4.20
release=1
depends=glibc
source=https://ftp.gnu.org/gnu/m4/m4-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
