#!/usr/bin/bash

name=patch
version=2.8
release=1
depends=glibc,attr
source=https://ftp.gnu.org/gnu/patch/patch-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
