#!/usr/bin/bash

name=e2fsprogs
version=1.47.3
release=1
depends=glibc,util-linux
source=https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v$version/e2fsprogs-$version.tar.gz
license="GPL-2.0-only"

build()
{
    mkdir build
    cd build
    ../configure --prefix=/usr      \
                --sysconfdir=/etc   \
                --enable-elf-shlibs \
                --disable-libblkid  \
                --disable-libuuid   \
                --disable-uuidd     \
                --disable-fsck
    make
    make DESTDIR=$DESTDIR install
    rm -f $DESTDIR/usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
}
