#!/usr/bin/bash

NAME=eiwd
VERSION=2.22
RELEASE=1
DEPENDS=glibc
SOURCE=https://github.com/illiliti/eiwd/releases/download/$VERSION-1/iwd-$VERSION.tar.xz
LICENSE=""

build()
{
    ./configure               \
        --prefix=/usr         \
        --libexecdir=/usr/bin \
        --localstatedir=/var  \
        --disable-dbus
    make
    make DESTDIR=$DESTDIR install
    install -Dm644 $RECIPE/daemon $DESTDIR/etc/init.d/iwd
}
