#!/usr/bin/bash

NAME=pkgconf
VERSION=2.5.1
RELEASE=1
DEPENDS=glibc
SOURCE=https://distfiles.ariadne.space/pkgconf/pkgconf-$VERSION.tar.xz
LICENSE="ISC"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
    ln -s pkgconf   $DESTDIR/usr/bin/pkg-config
    ln -s pkgconf.1 $DESTDIR/usr/share/man/man1/pkg-config.1
}
