#!/usr/bin/bash

name=pkgconf
version=2.5.1
release=1
depends=glibc
source=https://distfiles.ariadne.space/pkgconf/pkgconf-$version.tar.xz
license="ISC"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
    ln -s pkgconf   $DESTDIR/usr/bin/pkg-config
    ln -s pkgconf.1 $DESTDIR/usr/share/man/man1/pkg-config.1
}
