#!/usr/bin/bash

name=git
version=2.50.1
release=1
depends=glibc,curl,expat,perl,openssl,grep,shadow,zlib
source=https://www.kernel.org/pub/software/scm/git/git-$version.tar.xz
license="GPL-2.0-only"

build()
{
   ./configure --prefix=/usr \
            --with-gitconfig=/etc/gitconfig \
            --with-python=python3
    make
    make DESTDIR=$DESTDIR NO_INSTALL_HARDLINKS=1 perllibdir=/usr/lib/perl5/5.42/site_perl install 
}
