#!/usr/bin/bash

NAME=git
VERSION=2.50.1
RELEASE=1
DEPENDS=glibc,curl,expat,perl,openssl,grep,shadow,zlib
SOURCE=https://www.kernel.org/pub/software/scm/git/git-$VERSION.tar.xz
LICENSE="GPL-2.0-only"

build()
{
   ./configure --prefix=/usr \
            --with-gitconfig=/etc/gitconfig \
            --with-python=python3
    make
    make DESTDIR=$DESTDIR NO_INSTALL_HARDLINKS=1 perllibdir=/usr/lib/perl5/5.42/site_perl install 
}
