#!/usr/bin/bash

name=udev-lfs
version=20230818
release=1
depends=sh
source=https://anduin.linuxfromscratch.org/LFS/udev-lfs-$version.tar.xz
license="MIT"

build()
{
    cd ..
    make DESTDIR=$DESTDIR -f udev-lfs-20230818/Makefile.lfs install
}
