#!/usr/bin/bash

name=less
version=679
release=1
depends=glibc,ncurses
source=https://www.greenwoodsoftware.com/less/less-$version.tar.gz
license="GPL-3.0-or-later OR LicenseRef-Less"

build()
{
    ./configure --prefix=/usr --sysconfdir=/etc
    make
    make DESTDIR=$DESTDIR install
}
