#!/usr/bin/bash

NAME=kbd
VERSION=2.8.0
RELEASE=1
DEPENDS=glibc,gzip
SOURCE=https://www.kernel.org/pub/linux/utils/kbd/kbd-$VERSION.tar.xz
LICENSE="GPL-2.0-or-later"

build()
{
    sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
    sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in
    ./configure --prefix=/usr --disable-vlock
    make
    make DESTDIR=$DESTDIR install
}
