#!/usr/bin/bash

name=kbd
version=2.8.0
release=1
depends=glibc,gzip
source=https://www.kernel.org/pub/linux/utils/kbd/kbd-$version.tar.xz
license="GPL-2.0-or-later"

build()
{
    sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
    sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in
    ./configure --prefix=/usr --disable-vlock
    make
    make DESTDIR=$DESTDIR install
}
