#!/usr/bin/bash

name=ninja
version=1.13.1
release=1
depends=glibc,gcc
source=https://github.com/ninja-build/ninja/archive/v$version/ninja-$version.tar.gz
license="Apache-2.0"

build()
{
    python3 configure.py --bootstrap
    install -Dm755 ninja $DESTDIR/usr/bin/ninja
    install -Dm644 misc/bash-completion $DESTDIR/usr/share/bash-completion/completions/ninja
    install -Dm644 misc/zsh-completion  $DESTDIR/usr/share/zsh/site-functions/_ninja
}
