#!/usr/bin/bash

NAME=sh
VERSION=0.5.13
RELEASE=1
DEPENDS=glibc
SOURCE=http://gondor.apana.org.au/~herbert/dash/files/dash-$VERSION.tar.gz
LICENSE="BSD-3-Clause OR GPL-2.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    ln -s dash $DESTDIR/usr/bin/sh
}
