#!/usr/bin/bash

name=sh
version=0.5.13
release=1
depends=glibc
source=http://gondor.apana.org.au/~herbert/dash/files/dash-$version.tar.gz
license="BSD-3-Clause OR GPL-2.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    ln -s dash $DESTDIR/usr/bin/sh
}
