#!/usr/bin/bash

name=meow-config
version=1.0.0
release=1

build()
{
    mkdir -p $DESTDIR/{etc,var} $DESTDIR/usr/{bin,lib,sbin}
    
    for i in bin lib sbin; do
        ln -s usr/$i $DESTDIR/$i
    done
    
    case $(uname -m) in
        x86_64) mkdir -p $DESTDIR/lib64 ;;
    esac
    
    # 7.2 Virtual kernel file systems
    mkdir -p $DESTDIR/{dev,proc,sys,run}
    
    # 7.5 creating directories  
    mkdir -p $DESTDIR/{boot,home,mnt,opt,srv}
    mkdir -p $DESTDIR/etc/{opt,sysconfig}
    mkdir -p $DESTDIR/lib/firmware
    mkdir -p $DESTDIR/media/{floppy,cdrom}
    mkdir -p $DESTDIR/usr/{,local/}{include,src}
    mkdir -p $DESTDIR/usr/lib/locale
    mkdir -p $DESTDIR/usr/local/{bin,lib,sbin}
    mkdir -p $DESTDIR/usr/{,local/}share/{color,dict,doc,info,locale,man}
    mkdir -p $DESTDIR/usr/{,local/}share/{misc,terminfo,zoneinfo}
    mkdir -p $DESTDIR/usr/{,local/}share/man/man{1..8}
    mkdir -p $DESTDIR/var/{cache,local,log,mail,opt,spool}
    mkdir -p $DESTDIR/var/lib/{color,misc,locate}
    ln -sf /run $DESTDIR/var/run
    ln -sf /run/lock $DESTDIR/var/lock
    install -d -m 0750 $DESTDIR/root
    install -d -m 1777 $DESTDIR/tmp $DESTDIR/var/tmp

    echo 12.4 > $DESTDIR/etc/lfs-release   
    cp -r $recipe/etc/* $DESTDIR/etc/
}
