#!/usr/bin/bash

name=libffi
version=3.5.2
release=1
depends=glibc
source=https://github.com/libffi/libffi/releases/download/v$version/libffi-$version.tar.gz
license="MIT"

build()
{
    ./configure --prefix=/usr --disable-static --without-gcc-arch
    make
    make DESTDIR=$DESTDIR install
}
