#!/usr/bin/bash

name=expat
version=2.7.1
release=1
depends=glibc
source=https://github.com/libexpat/libexpat/releases/download/R_${version//./_}/expat-$version.tar.xz
license="MIT"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
}
