#!/usr/bin/bash

NAME=expat
VERSION=2.7.1
RELEASE=1
DEPENDS=glibc
SOURCE=https://github.com/libexpat/libexpat/releases/download/R_${VERSION//./_}/expat-$VERSION.tar.xz
LICENSE="MIT"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
}
