#!/usr/bin/bash

name=libxcrypt
version=4.4.38
release=1
depends=glibc
source=https://github.com/besser82/libxcrypt/releases/download/v$version/libxcrypt-$version.tar.xz
license="LGPL"

build()
{
    ./configure --prefix=/usr                \
                --enable-hashes=strong,glibc \
                --enable-obsolete-api=no     \
                --disable-static             \
                --disable-failure-tokens
    make
    make DESTDIR=$DESTDIR install
}
