#!/usr/bin/bash

name=gettext
version=0.26
release=1
depends=glibc,acl,attr,gcc,ncurses,sh,libxml2
source=https://ftp.gnu.org/gnu/gettext/gettext-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
    chmod 0755 $DESTDIR/usr/lib/preloadable_libintl.so
}
