#!/usr/bin/bash

NAME=automake
VERSION=1.18.1
RELEASE=1
DEPENDS=glibc,perl,bash
SOURCE=https://ftp.gnu.org/gnu/automake/automake-$VERSION.tar.xz

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
