#!/usr/bin/bash

name=automake
version=1.18.1
release=1
depends=glibc,perl,bash
source=https://ftp.gnu.org/gnu/automake/automake-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
