#!/usr/bin/bash

name=iproute2
version=6.16.0
release=1
depends=glibc,libcap,libelf
source=https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-$version.tar.xz
license="GPL-2.0-or-later"

build()
{
    sed -i /ARPD/d Makefile
    rm -f man/man8/arpd.8
    make NETNS_RUN_DIR=/run/netns
    make DESTDIR=$DESTDIR SBINDIR=/usr/sbin install
}
