#!/usr/bin/bash

NAME=gperf
VERSION=3.3
RELEASE=1
DEPENDS=glibc,gcc
SOURCE=https://ftp.gnu.org/gnu/gperf/gperf-$VERSION.tar.gz
LICENSE="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
