#!/usr/bin/bash

name=gperf
version=3.3
release=1
depends=glibc,gcc
source=https://ftp.gnu.org/gnu/gperf/gperf-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
