#!/usr/bin/bash

NAME=mpc
VERSION=1.3.1
RELEASE=1
DEPENDS=glibc
SOURCE=https://ftp.gnu.org/gnu/mpc/mpc-$VERSION.tar.gz
LICENSE="GPL-2.0-or-later"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
}
