#!/usr/bin/bash

name=mpc
version=1.3.1
release=1
depends=glibc
source=https://ftp.gnu.org/gnu/mpc/mpc-$version.tar.gz
license="GPL-2.0-or-later"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
}
