#!/usr/bin/bash

name=grep
version=3.12
release=1
depends=glibc,pcre2,sh
source=https://ftp.gnu.org/gnu/grep/grep-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    sed -i "s/echo/#echo/" src/egrep.sh
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
