#!/usr/bin/bash

name=bc
version=7.0.3
release=1
depends=glibc,readline
source=https://github.com/gavinhoward/bc/releases/download/$version/bc-$version.tar.xz
license="BSD-2-Clause"

build()
{
    CC='gcc -std=c99' ./configure --prefix=/usr -O3 --with-readline
    make
    make DESTDIR=$DESTDIR install
}
