#!/usr/bin/bash

name=fontconfig
version=2.17.1
release=1
depends=glibc,freetype,expat,bash
source=https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/$version/fontconfig-$version.tar.xz
license="HPND AND Unicode-DFS-2016"

build()
{
    ./configure --prefix=/usr        \
                --sysconfdir=/etc    \
                --localstatedir=/var \
                --disable-docs
    make
    make DESTDIR=$DESTDIR install
}
