#!/usr/bin/bash

name=lz4
version=1.10.0
release=1
depends=glibc
source=https://github.com/lz4/lz4/archive/refs/tags/v$version.tar.gz
license="GPL-2.0-or-later"

build()
{
    make BUILD_STATIC=no PREFIX=/usr
    make DESTDIR=$DESTDIR BUILD_STATIC=no PREFIX=/usr install
}
