#!/usr/bin/bash

name=perl-xml-parser
version=2.47
release=1
depends=expat
source=https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-$version.tar.gz
license="PerlArtistic"

build()
{
    perl Makefile.PL INSTALLDIRS=vendor
    make
    make DESTDIR=$DESTDIR install
}
