mkdir build
cd build
meson setup .. \
    -Dlink-boot-shared=false \
    --prefix=/usr \
    --buildtype=release \
    -Dsbat-distro-url="https://tilde.club/~aspizu" \
    -Dmode=release \
    -Dsysvinit-path= \
    -Dbootloader=enabled \
    -Dadm-group=false \
    -Danalyze=false \
    -Dapparmor=disabled \
    -Daudit=disabled \
    -Dbacklight=false \
    -Dbinfmt=false \
    -Dbpf-framework=disabled \
    -Dbzip2=disabled \
    -Dcoredump=false \
    -Ddbus=disabled \
    -Delfutils=disabled \
    -Denvironment-d=false \
    -Dfdisk=disabled \
    -Dgcrypt=disabled \
    -Dglib=disabled \
    -Dgshadow=false \
    -Dgnutls=disabled \
    -Dhibernate=false \
    -Dhostnamed=false \
    -Didn=false \
    -Dima=false \
    -Dinitrd=false \
    -Dfirstboot=false \
    -Dldconfig=false \
    -Dlibcryptsetup=disabled \
    -Dlibcurl=disabled \
    -Dlibfido2=disabled \
    -Dlibidn=disabled \
    -Dlibidn2=disabled \
    -Dlibiptc=disabled \
    -Dlocaled=false \
    -Dlogind=false \
    -Dlz4=disabled \
    -Dmachined=false \
    -Dmicrohttpd=disabled \
    -Dnetworkd=false \
    -Dnscd=false \
    -Dnss-myhostname=false \
    -Dnss-resolve=disabled \
    -Dnss-systemd=false \
    -Doomd=false \
    -Dopenssl=disabled \
    -Dp11kit=disabled \
    -Dpam=disabled \
    -Dpcre2=disabled \
    -Dpolkit=disabled \
    -Dportabled=false \
    -Dpstore=false \
    -Dpwquality=disabled \
    -Drandomseed=false \
    -Dresolve=false \
    -Drfkill=false \
    -Dseccomp=disabled \
    -Dsmack=false \
    -Dsysext=false \
    -Dtimedated=false \
    -Dtimesyncd=false \
    -Dtpm=false \
    -Dqrencode=disabled \
    -Dquotacheck=false \
    -Duserdb=false \
    -Dutmp=false \
    -Dvconsole=false \
    -Dwheel-group=false \
    -Dxdg-autostart=false \
    -Dxkbcommon=disabled \
    -Dxz=disabled \
    -Dzlib=disabled \
    -Dzstd=disabled
meson compile
install -Dm755 bootctl $DESTDIR/usr/bin/bootctl
_efiarch=x64
mkdir -p $DESTDIR/usr/bin/systemd/boot/efi
cp src/boot/{linux${_efiarch}.{efi,elf}.stub,systemd-boot${_efiarch}.efi} $DESTDIR/usr/lib/systemd/boot/efi
install -Dm755 kernel-install$DESTDIR/usr/bin/kernel-install
