#!/usr/bin/bash

name=texinfo
version=7.2
release=1
depends=glibc,ncurses,gzip,perl,sh
source=https://ftp.gnu.org/gnu/texinfo/texinfo-$version.tar.xz
license="GPL3"

build()
{
    sed 's/! $output_file eq/$output_file ne/' -i tp/Texinfo/Convert/*.pm
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
