#!/usr/bin/bash

NAME=texinfo
VERSION=7.2
RELEASE=1
DEPENDS=glibc,ncurses,gzip,perl,sh
SOURCE=https://ftp.gnu.org/gnu/texinfo/texinfo-$VERSION.tar.xz
LICENSE="GPL3"

build()
{
    sed 's/! $output_file eq/$output_file ne/' -i tp/Texinfo/Convert/*.pm
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
