#!/usr/bin/bash

name=util-linux
version=2.41.1
release=1
depends=glibc,coreutils,file,libcap,ncurses,libxcrypt,readline,shadow,zlib
source=https://www.kernel.org/pub/linux/utils/util-linux/v2.41/util-linux-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --bindir=/usr/bin     \
                --libdir=/usr/lib     \
                --runstatedir=/run    \
                --sbindir=/usr/sbin   \
                --disable-chfn-chsh   \
                --disable-login       \
                --disable-nologin     \
                --disable-su          \
                --disable-setpriv     \
                --disable-runuser     \
                --disable-pylibmount  \
                --disable-liblastlog2 \
                --disable-static      \
                --without-python      \
                --without-systemd     \
                --without-systemdsystemunitdir        \
                ADJTIME_PATH=/var/lib/hwclock/adjtime
    make
    make DESTDIR=$DESTDIR install
}
