#!/usr/bin/bash

name=iwd
version=3.10
release=1
depends=glibc,gcc,sh
source=https://github.com/ioraff/eiwd/releases/download/3.10-1/iwd-3.10.tar.xz
license="LGPL-2.1-or-later"

build()
{
    ./configure               \
        --prefix=/usr         \
        --libexecdir=/usr/bin \
        --localstatedir=/var  \
        --disable-dbus
    make
    make DESTDIR=$DESTDIR install
    install -Dm644 $recipe/daemon $DESTDIR/etc/init.d/iwd
}
