#!/usr/bin/bash

NAME=libpipeline
VERSION=1.5.8
RELEASE=1
DEPENDS=glibc
SOURCE=https://download.savannah.gnu.org/releases/libpipeline/libpipeline-$VERSION.tar.gz
LICENSE="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
