#!/usr/bin/bash

name=libpipeline
version=1.5.8
release=1
depends=glibc
source=https://download.savannah.gnu.org/releases/libpipeline/libpipeline-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
