#!/bin/sh
########################################################################
# Begin iwd
#
# Description : Start iwd daemon
#
# Author      : aspizu - aspizu@protonmail.com
#
# Version     : meowOS 12.4
#
########################################################################

### BEGIN INIT INFO
# Provides:            iwd
# Required-Start:      $network
# Should-Start:        
# Required-Stop:       $network
# Should-Stop:         
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts iwd daemon.
# Description:         Starts iwd daemon.
# X-LFS-Provided-By:   meowOS
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
        log_info_msg "Starting Intel Wireless Daemon..."
        start_daemon -f /usr/bin/iwd
        evaluate_retval
        ;;
    stop)
        log_info_msg "Stopping Intel Wireless Daemon..."
        killproc /usr/bin/iwd
        evaluate_retval
        ;;
    reload|restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        statusproc /usr/bin/iwd
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
        ;;
esac
