#!/usr/bin/bash

name=libxml2
version=2.14.5
release=1
depends=glibc,bash,icu,readline,zlib
source=https://download.gnome.org/sources/libxml2/2.14/libxml2-$version.tar.xz
license="MIT"

build()
{
    ./configure --prefix=/usr     \
                --sysconfdir=/etc \
                --disable-static  \
                --with-history    \
                --with-icu        \
                PYTHON=/usr/bin/python3
    make
    make DESTDIR=$DESTDIR install
    rm $DESTDIR/usr/lib/libxml2.la
    sed '/libs=/s/xml2.*/xml2"/' -i $DESTDIR/usr/bin/xml2-config
}
