#!/usr/bin/bash

NAME=libxml2
VERSION=2.14.5
RELEASE=1
DEPENDS=glibc,bash,icu,readline,zlib
SOURCE=https://download.gnome.org/sources/libxml2/2.14/libxml2-$VERSION.tar.xz
LICENSE="MIT"

build()
{
    ./configure --prefix=/usr     \
                --sysconfdir=/etc \
                --disable-static  \
                --with-history    \
                --with-icu        \
                PYTHON=/usr/bin/python3
    make
    make DESTDIR=$DESTDIR install
    rm $DESTDIR/usr/lib/libxml2.la
    sed '/libs=/s/xml2.*/xml2"/' -i $DESTDIR/usr/bin/xml2-config
}
