#!/usr/bin/bash

name=libtasn1
version=4.20.0
release=1
depends=glibc
source=https://ftp.gnu.org/gnu/libtasn1/libtasn1-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
}
