#!/usr/bin/bash

name=make-ca
version=1.16.1
release=1
depends=openssl,p11-kit,coreutils,sed,gawk
source=https://github.com/lfs-book/make-ca/archive/v$version/make-ca-$version.tar.gz
license="MIT"

build()
{
    make DESTDIR=$DESTDIR install
    install -vdm755 $DESTDIR/etc/ssl/local
    mv LICENSE.MIT LICENSE
}
