#!/usr/bin/bash

NAME=openssl
VERSION=3.5.2
RELEASE=1
DEPENDS=glibc,zlib,zstd
SOURCE=https://github.com/openssl/openssl/releases/download/openssl-$VERSION/openssl-$VERSION.tar.gz
LICENSE="Apache-2.0"

build()
{
    ./config --prefix=/usr         \
             --openssldir=/etc/ssl \
             --libdir=lib          \
             shared                \
             zlib-dynamic
    make
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
    make DESTDIR=$DESTDIR MANSUFFIX=ssl install
}
