#!/usr/bin/bash

name=openssl
version=3.5.2
release=1
depends=glibc,zlib,zstd
source=https://github.com/openssl/openssl/releases/download/openssl-$version/openssl-$version.tar.gz
license="Apache-2.0"

build()
{
    ./config --prefix=/usr         \
             --openssldir=/etc/ssl \
             --libdir=lib          \
             shared                \
             zlib-dynamic
    make
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
    make DESTDIR=$DESTDIR MANSUFFIX=ssl install
}
