#!/usr/bin/bash

name=intltool
version=0.51.0
release=1
depends=perl,perl-xml-parser
source=https://launchpad.net/intltool/trunk/$version/+download/intltool-$version.tar.gz
license="GPL-2.0-only"

build()
{
    sed -i 's:\\\${:\\\$\\{:' intltool-update.in
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
