#!/usr/bin/bash

name=libtool
version=2.5.4
release=1
depends=glibc,sh,tar
source=https://ftp.gnu.org/gnu/libtool/libtool-$version.tar.xz
license="LGPL-2.0-or-later WITH Libtool-exception"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    rm -f $DESTDIR/usr/lib/libltdl.a
}
