#!/usr/bin/bash

NAME=openresolv
VERSION=3.17.0
RELEASE=1
DEPENDS=bash
SOURCE=https://github.com/NetworkConfiguration/openresolv/releases/download/v$VERSION/openresolv-$VERSION.tar.xz
LICENSE="BSD-2-Clause"

build()
{
    ./configure --prefix=/usr --sbindir=/usr/bin --sysconfdir=/etc
    make
    make DESTDIR=$DESTDIR install
}
