#!/usr/bin/bash

name=openresolv
version=3.17.0
release=1
depends=bash
source=https://github.com/NetworkConfiguration/openresolv/releases/download/v$version/openresolv-$version.tar.xz
license="BSD-2-Clause"

build()
{
    ./configure --prefix=/usr --sbindir=/usr/bin --sysconfdir=/etc
    make
    make DESTDIR=$DESTDIR install
}
