#!/usr/bin/bash

NAME=gcc
VERSION=15.2.0
RELEASE=1
DEPENDS=glibc,binutils,mpc,zlib,zstd
SOURCE=https://ftp.gnu.org/gnu/gcc/gcc-$VERSION/gcc-$VERSION.tar.xz
LICENSE="GPL-3.0-or-later"

build()
{
    case $(uname -m) in
        x86_64)
            sed -e '/m64=/s/lib64/lib/' \
                -i.orig gcc/config/i386/t-linux64
        ;;
    esac
    mkdir build
    cd build
    ../configure --prefix=/usr           \
                LD=ld                    \
                --enable-languages=c,c++ \
                --enable-default-pie     \
                --enable-default-ssp     \
                --enable-host-pie        \
                --disable-multilib       \
                --disable-bootstrap      \
                --disable-fixincludes    \
                --with-system-zlib
    make
    make DESTDIR=$DESTDIR install
    mkdir -p $DESTDIR/usr/lib/bfd-plugins
    ln -sr /usr/bin/cpp $DESTDIR/usr/lib
    ln -s gcc $DESTDIR/usr/bin/cc
    ln -s gcc.1 $DESTDIR/usr/share/man/man1/cc.1
    ln -sf ../../libexec/gcc/$(gcc -dumpmachine)/15.2.0/liblto_plugin.so \
            $DESTDIR/usr/lib/bfd-plugins/
    mkdir -p $DESTDIR/usr/share/gdb/auto-load/usr/lib
    mv $DESTDIR/usr/lib/*gdb.py $DESTDIR/usr/share/gdb/auto-load/usr/lib
}
