#!/usr/bin/bash

name=file
version=5.46
release=1
depends=glibc,bzip2,xz,zlib,zstd
source=https://astron.com/pub/file/file-$version.tar.gz

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
