#!/usr/bin/bash

name=readline
version=8.3
release=1
depends=glibc,ncurses
source=https://ftp.gnu.org/gnu/readline/readline-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    sed -i '/MV.*old/d' Makefile.in
    sed -i '/{OLDSUFF}/c:' support/shlib-install
    sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf
    ./configure --prefix=/usr    \
                --disable-static \
                --with-curses
    make SHLIB_LIBS="-lncursesw"
    make DESTDIR=$DESTDIR install
}
