#!/usr/bin/bash

NAME=readline
VERSION=8.3
RELEASE=1
DEPENDS=glibc,ncurses
SOURCE=https://ftp.gnu.org/gnu/readline/readline-$VERSION.tar.gz
LICENSE="GPL-3.0-or-later"

build()
{
    sed -i '/MV.*old/d' Makefile.in
    sed -i '/{OLDSUFF}/c:' support/shlib-install
    sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf
    ./configure --prefix=/usr    \
                --disable-static \
                --with-curses
    make SHLIB_LIBS="-lncursesw"
    make DESTDIR=$DESTDIR install
}
