#!/usr/bin/bash

name=binutils
version=2.45
release=1
depends=glibc,zlib,zstd,libelf
source=https://sourceware.org/pub/binutils/releases/binutils-$version.tar.xz
license="GPL-2.0-or-later OR GPL-3.0-or-later"

build()
{
    mkdir build
    cd build
    ../configure --prefix=/usr      \
                --sysconfdir=/etc   \
                --enable-ld=default \
                --enable-plugins    \
                --enable-shared     \
                --disable-werror    \
                --enable-64-bit-bfd \
                --enable-new-dtags  \
                --with-system-zlib  \
                --enable-default-hash-style=gnu
    make tooldir=/usr
    make DESTDIR=$DESTDIR tooldir=/usr install
    rm -rf $DESTDIR/usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a $DESTDIR/usr/share/doc/gprofng/
}
