#!/usr/bin/bash

name=libcap
version=2.76
release=1
depends=glibc
source=https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-$version.tar.xz
license="BSD-3-Clause OR GPL-2.0-only"

build()
{
    sed -i '/install -m.*STA/d' libcap/Makefile
    make prefix=/usr lib=lib
    make DESTDIR=$DESTDIR prefix=/usr lib=lib install
}
