#!/usr/bin/bash

NAME=mpfr
VERSION=4.2.2
RELEASE=1
DEPENDS=glibc,gmp
SOURCE=https://ftp.gnu.org/gnu/mpfr/mpfr-$VERSION.tar.xz
LICENSE="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr        \
                --disable-static     \
                --enable-thread-safe
    make
    make DESTDIR=$DESTDIR install
}
