#!/usr/bin/bash

name=mpfr
version=4.2.2
release=1
depends=glibc,gmp
source=https://ftp.gnu.org/gnu/mpfr/mpfr-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr        \
                --disable-static     \
                --enable-thread-safe
    make
    make DESTDIR=$DESTDIR install
}
