#!/usr/bin/bash

name=lfs-bootscripts
version=20250827
release=1
depends=sysvinit,sh
source=https://www.linuxfromscratch.org/lfs/downloads/12.4/lfs-bootscripts-$version.tar.xz
license="MIT"

build()
{
    make DESTDIR=$DESTDIR install
}
