#!/usr/bin/bash

name=autoconf
version=2.72
release=1
depends=glibc,gawk,m4,diffutils,perl,sh
source=https://ftp.gnu.org/gnu/autoconf/autoconf-$version.tar.xz
license="GPL2.0-or-later OR GPL3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
