#!/usr/bin/bash

name=wget
version=1.25.0
release=1
depends=glibc,zlib,openssl,util-linux,libpsl,libidn2,make-ca
source=https://ftp.gnu.org/gnu/wget/wget-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --sysconfdir=/etc --with-ssl=openssl
    make
    make DESTDIR=$DESTDIR install
}
