#!/usr/bin/bash

NAME=wget
VERSION=1.25.0
RELEASE=1
DEPENDS=glibc,zlib,openssl,util-linux,libpsl,libidn2,make-ca
SOURCE=https://ftp.gnu.org/gnu/wget/wget-$VERSION.tar.gz
LICENSE="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --sysconfdir=/etc --with-ssl=openssl
    make
    make DESTDIR=$DESTDIR install
}
