#!/usr/bin/bash

name=kakoune
version=2025.06.03
release=1
depends=glibc
source=https://github.com/mawww/kakoune/releases/download/v$version/kakoune-$version.tar.bz2
license="Unlicense"

build()
{
    make
    make PREFIX=/usr DESTDIR=$DESTDIR install
}
