#!/usr/bin/bash

name=psmisc
version=23.7
release=1
depends=glibc,ncurses
source=https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$version.tar.xz
license="GPL"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
