#!/usr/bin/bash

name=attr
version=2.5.2
release=1
depends=glibc
source=https://download.savannah.gnu.org/releases/attr/attr-$version.tar.gz
license="LGPL-2.1-or-later AND GPL-2.0-or-later"

build()
{
    ./configure --prefix=/usr     \
                --disable-static  \
                --sysconfdir=/etc
    make
    make DESTDIR=$DESTDIR install
}
