#!/usr/bin/bash

name=libelf
version=0.193
release=1
depends=zlib,zstd,xz,bzip2,glibc
source=https://sourceware.org/ftp/elfutils/$version/elfutils-$version.tar.bz2
license="GPL-2.0-or-later OR LGPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --disable-debuginfod --enable-libdebuginfod=dummy
    make
    make -C libelf DESTDIR=$DESTDIR install
    install -Dm644 config/libelf.pc $DESTDIR/usr/lib/pkgconfig/libelf.pc
    rm $DESTDIR/usr/lib/libelf.a
}
