#!/usr/bin/bash

NAME=procps-ng
VERSION=4.0.5
RELEASE=1
DEPENDS=glibc,ncurses
SOURCE=https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-$VERSION.tar.xz
LICENSE="LGPL"

build()
{
    ./configure --prefix=/usr                           \
                --docdir=/usr/share/doc/procps-ng-4.0.5 \
                --disable-static                        \
                --disable-kill                          \
                --enable-watch8bit
    make
    make DESTDIR=$DESTDIR install
}
