#!/usr/bin/bash

name=procps-ng
version=4.0.5
release=1
depends=glibc,ncurses
source=https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-$version.tar.xz
license="LGPL"

build()
{
    ./configure --prefix=/usr                           \
                --docdir=/usr/share/doc/procps-ng-4.0.5 \
                --disable-static                        \
                --disable-kill                          \
                --enable-watch8bit
    make
    make DESTDIR=$DESTDIR install
}
