#!/usr/bin/bash

name=bison
version=3.8.2
release=1
depends=glibc,gettext,m4,sh
source=https://ftp.gnu.org/gnu/bison/bison-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
