#!/usr/bin/bash

name=diffutils
version=3.12
release=1
depends=glibc
source=https://ftp.gnu.org/gnu/diffutils/diffutils-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
