#!/usr/bin/bash

name=zstd
version=1.5.7
release=1
depends=glibc,gcc,zlib,xz,lz4
source=https://github.com/facebook/zstd/archive/refs/tags/v$version.tar.gz
license="BSD-3-Clause OR GPL-2.0-only"

build()
{
    make prefix=/usr           \
         HAVE_THREAD=1         \
         ZSTD_LEGACY_SUPPORT=1 \
         HAVE_ZLIB=1           \
         HAVE_LZMA=1           \
         HAVE_LZ4=1
    make prefix=/usr install
    rm $DESTDIR/usr/lib/libzstd.a
}
