#!/usr/bin/bash

name=findutils
version=4.10.0
release=1
depends=glibc
source=https://ftp.gnu.org/gnu/findutils/findutils-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --localstatedir=/var/lib/locate
    make
    make DESTDIR=$DESTDIR install
}
