#!/usr/bin/bash

NAME=findutils
VERSION=4.10.0
RELEASE=1
DEPENDS=glibc
SOURCE=https://ftp.gnu.org/gnu/findutils/findutils-$VERSION.tar.xz
LICENSE="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr --localstatedir=/var/lib/locate
    make
    make DESTDIR=$DESTDIR install
}
