#!/usr/bin/bash

NAME=gawk
VERSION=5.3.2
RELEASE=1
DEPENDS=glibc,mpfr,sh
SOURCE=https://ftp.gnu.org/gnu/gawk/gawk-$VERSION.tar.xz
LICENSE="GPL-3.0-or-later"

build()
{
    sed -i 's/extras//' Makefile.in
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    ln -sv gawk.1 $DESTDIR/usr/share/man/man1/awk.1
}
