#!/usr/bin/bash

name=gawk
version=5.3.2
release=1
depends=glibc,mpfr,sh
source=https://ftp.gnu.org/gnu/gawk/gawk-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    sed -i 's/extras//' Makefile.in
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    ln -sv gawk.1 $DESTDIR/usr/share/man/man1/awk.1
}
