#!/usr/bin/bash

name=gdbm
version=1.26
release=1
depends=glibc,sh
source=https://ftp.gnu.org/gnu/gdbm/gdbm-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr    \
                --disable-static \
                --enable-libgdbm-compat
    make
    make DESTDIR=$DESTDIR install
}
