#!/usr/bin/bash

name=sed
version=4.9
release=1
depends=glibc,acl
source=https://ftp.gnu.org/gnu/sed/sed-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
