#!/usr/bin/bash

name=make
version=4.4.1
release=1
depends=glibc
source=https://ftp.gnu.org/gnu/make/make-$version.tar.gz
license="GPL3"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
