#!/usr/bin/bash

NAME=make
VERSION=4.4.1
RELEASE=1
DEPENDS=glibc
SOURCE=https://ftp.gnu.org/gnu/make/make-$VERSION.tar.gz
LICENSE="GPL3"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
