#!/usr/bin/bash

name=gmp
version=6.3.0
release=1
depends=glibc,gcc
source=https://ftp.gnu.org/gnu/gmp/gmp-$version.tar.xz
license="LGPL-3.0-or-later"

build()
{
    sed -i '/long long t1;/,+1s/()/(...)/' configure
    ./configure --prefix=/usr    \
                --enable-cxx     \
                --disable-static \
                --host=none-linux-gnu
    make
    make DESTDIR=$DESTDIR install
}
