#!/usr/bin/bash

name=flex
version=2.6.4
release=1
depends=glibc,m4,sh
source=https://github.com/westes/flex/releases/download/v$version/flex-$version.tar.gz

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
    ln -s flex   $DESTDIR/usr/bin/lex
    ln -s flex.1 $DESTDIR/usr/share/man/man1/lex.1
}
