#!/usr/bin/bash

NAME=flex
VERSION=2.6.4
RELEASE=1
DEPENDS=glibc,m4,sh
SOURCE=https://github.com/westes/flex/releases/download/v$VERSION/flex-$VERSION.tar.gz

build()
{
    ./configure --prefix=/usr --disable-static
    make
    make DESTDIR=$DESTDIR install
    ln -s flex   $DESTDIR/usr/bin/lex
    ln -s flex.1 $DESTDIR/usr/share/man/man1/lex.1
}
