#!/usr/bin/bash

name=tar
version=1.35
release=1
depends=glibc,acl
source=https://ftp.gnu.org/gnu/tar/tar-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
