#!/usr/bin/bash

NAME=linux-headers
VERSION=6.16.1
RELEASE=1
SOURCE=https://www.kernel.org/pub/linux/kernel/v6.x/linux-$VERSION.tar.xz
LICENSE="GPL-2.0-only"

build()
{
    make mrproper
    make headers
    find usr/include -type f ! -name '*.h' -delete
    mkdir -p $DESTDIR/usr/include
    cp -r usr/include $DESTDIR/usr
}
