#!/usr/bin/bash

name=linux-headers
version=6.16.1
release=1
source=https://www.kernel.org/pub/linux/kernel/v6.x/linux-$version.tar.xz
license="GPL-2.0-only"

build()
{
    make mrproper
    make headers
    find usr/include -type f ! -name '*.h' -delete
    mkdir -p $DESTDIR/usr/include
    cp -r usr/include $DESTDIR/usr
}
