#!/usr/bin/bash

name=perl
version=5.42.0
release=1
depends=glibc,gdbm,libxcrypt
source=https://www.cpan.org/src/5.0/perl-$version.tar.xz
license="Artistic-1.0-Perl OR GPL-1.0-or-later"

build()
{
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    sh Configure -des                                          \
                 -D prefix=/usr                                \
                 -D vendorprefix=/usr                          \
                 -D privlib=/usr/lib/perl5/5.42/core_perl      \
                 -D archlib=/usr/lib/perl5/5.42/core_perl      \
                 -D sitelib=/usr/lib/perl5/5.42/site_perl      \
                 -D sitearch=/usr/lib/perl5/5.42/site_perl     \
                 -D vendorlib=/usr/lib/perl5/5.42/vendor_perl  \
                 -D vendorarch=/usr/lib/perl5/5.42/vendor_perl \
                 -D man1dir=/usr/share/man/man1                \
                 -D man3dir=/usr/share/man/man3                \
                 -D pager="/usr/bin/less -isR"                 \
                 -D useshrplib                                 \
                 -D usethreads
    make
    make DESTDIR=$DESTDIR install
}
