#!/usr/bin/bash

name=gzip
version=1.14
release=1
depends=glibc,sh,coreutils,sed
source=https://ftp.gnu.org/gnu/gzip/gzip-$version.tar.xz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
}
