#!/usr/bin/bash

name=pixman
version=0.46.4
release=1
depends=glibc
source=https://www.cairographics.org/releases/pixman-$version.tar.gz
license="MIT"

build()
{
    meson setup --prefix=/usr --buildtype=release build
    ninja -C build
    meson install -C build
}
