#!/usr/bin/bash

name=tzdata
version=2025b
release=1
source=https://www.iana.org/time-zones/repository/releases/tzdata$version.tar.gz
license="LicenseRef-tz"

build()
{
    ZONEINFO=$DESTDIR/usr/share/zoneinfo
    mkdir -pv $ZONEINFO/{posix,right}
    for tz in etcetera southamerica northamerica europe africa antarctica  \
              asia australasia backward; do
        zic -L /dev/null   -d $ZONEINFO       ${tz}
        zic -L /dev/null   -d $ZONEINFO/posix ${tz}
        zic -L leapseconds -d $ZONEINFO/right ${tz}
    done
    
    cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
    zic -d $ZONEINFO -p America/New_York
}
