#!/usr/bin/bash

name=iana-etc
version=20251016
release=1
source=https://github.com/Mic92/iana-etc/releases/download/$version/iana-etc-$version.tar.gz

build()
{
    install -D services $DESTDIR/etc/services
    install -D protocols $DESTDIR/etc/protocols
}
