#!/usr/bin/bash

NAME=sysklogd
VERSION=2.7.2
RELEASE=1
DEPENDS=glibc,util-linux
SOURCE=https://github.com/troglobit/sysklogd/releases/download/v$VERSION/sysklogd-$VERSION.tar.gz
LICENSE=""

build()
{
    ./configure --prefix=/usr      \
                --sysconfdir=/etc  \
                --runstatedir=/run \
                --without-logger   \
                --disable-static
    make
    make DESTDIR=$DESTDIR install
    mkdir $DESTDIR/etc
    cat > $DESTDIR/etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# Do not open any internet ports.
secure_mode 2

# End /etc/syslog.conf
EOF
}
