#!/usr/bin/bash

name=cmake
version=4.1.0
release=1
depends=glibc,curl,ncurses,zlib,expat,gcc
source=https://cmake.org/files/v${VERSION%.*}/cmake-$version.tar.gz
license="BSD-3-Clause"

build()
{
    sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake

    ./bootstrap --prefix=/usr          \
                --system-libs          \
                --mandir=/share/man    \
                --no-system-jsoncpp    \
                --no-system-cppdap     \
                --no-system-librhash   \
                --no-system-libarchive \
                --no-system-libuv
    make
    make DESTDIR=$DESTDIR install
}
