#!/usr/bin/bash

NAME=bash
VERSION=5.3
RELEASE=1
DEPENDS=glibc,readline,ncurses
SOURCE=https://ftp.gnu.org/gnu/bash/bash-$VERSION.tar.gz
LICENSE="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr             \
                --without-bash-malloc     \
                --with-installed-readline
    make
    make DESTDIR=$DESTDIR install
}
