#!/usr/bin/bash

name=bash
version=5.3
release=1
depends=glibc,readline,ncurses
source=https://ftp.gnu.org/gnu/bash/bash-$version.tar.gz
license="GPL-3.0-or-later"

build()
{
    ./configure --prefix=/usr             \
                --without-bash-malloc     \
                --with-installed-readline
    make
    make DESTDIR=$DESTDIR install
}
