#!/usr/bin/bash

name=curl
version=8.15.0
release=1
depends=glibc,openssl,make-ca,libidn2,libpsl,zlib,zstd
source=https://curl.se/download/curl-$version.tar.xz
license="curl"

build()
{
    ./configure --prefix=/usr    \
                --disable-static \
                --with-openssl   \
                --with-ca-path=/etc/ssl/certs
    make
    make DESTDIR=$DESTDIR install
}
