#!/usr/bin/bash

NAME=dash
VERSION=0.5.13
RELEASE=1
DEPENDS=glibc
SOURCE=http://gondor.apana.org.au/~herbert/dash/files/dash-$VERSION.tar.gz
LICENSE=""

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    ln -s dash $DESTDIR/usr/bin/sh
}
