#!/usr/bin/bash

name=dash
version=0.5.13
release=1
depends=glibc
source=http://gondor.apana.org.au/~herbert/dash/files/dash-$version.tar.gz
license=""

build()
{
    ./configure --prefix=/usr
    make
    make DESTDIR=$DESTDIR install
    ln -s dash $DESTDIR/usr/bin/sh
}
