#!/usr/bin/bash

NAME=zlib
VERSION=1.3.1
RELEASE=1
DEPENDS=glibc
SOURCE=https://zlib.net/zlib-$VERSION.tar.gz

build()
{
    ./configure --prefix=/usr
    make
    make install
    rm $DESTDIR/usr/lib/libz.a
}
