#!/usr/bin/bash

name=zlib
version=1.3.1
release=1
depends=glibc
source=https://zlib.net/zlib-$version.tar.gz
license="Zlib"

build()
{
    ./configure --prefix=/usr
    make
    make install
    rm $DESTDIR/usr/lib/libz.a
}
